#!/usr/bin/env python3
# Use this to generate the test cases for alu.t.sv

import itertools

leading = "\t\t"

aOpts = [0, 1, -1, 2**31-1, -2**31]
bOpts = [0, 1, -1, 2**31-1, -2**31]
cmdOpts = [0, 1, 2, 3, 4, 5, 6, 7]

cases = list(itertools.product(*[aOpts, bOpts, cmdOpts]))

def numTo32d(x):
  if x < 0:
    return "-32'd" + str(-x)
  else:
    return "32'd" + str(x)

print(leading + "// Auto-generated by timing-test-cases.py")
for i, case in enumerate(cases):
  print(
      leading + "testA[" + str(i) + "]=" + numTo32d(case[0]) + "; " + 
    "testB[" + str(i) + "]=" + numTo32d(case[1]) + "; " + 
    "testCmd[" + str(i) + "]=3'd" + str(case[2]) + "; "
    )
print(leading + "// End auto-generated")
