@startuml
[A_i]
[B_i]
[Carry_i]

package "Inverting Stage" {
        [A_i] --> [AND || OR ? Invert]
        [B_i] --> [AND || OR || SUB || SLT ? Invert]
}

package "Combining Stage" {
        [AND || OR ? Invert] --> [ADD]
        [AND || OR || SUB || SLT ? Invert] --> [ADD]
        [Carry_i] --> [ADD]

        [AND || OR ? Invert] --> [NOR]
        [AND || OR || SUB || SLT ? Invert] --> [NOR]

        [AND || OR ? Invert] --> [NAND]
        [AND || OR || SUB || SLT ? Invert] --> [NAND]

        [AND || OR ? Invert] --> [XOR]
        [AND || OR || SUB || SLT ? Invert] --> [XOR]
}

package "Selection Stage" {
        [ADD] --> [Out_i, Carry_i+1]
        [NOR] --> [Out_i, Carry_i+1]
        [NAND] --> [Out_i, Carry_i+1]
        [XOR] --> [Out_i, Carry_i+1]
}

@enduml
