@startuml
[A_0]
[B_0]

package "Inverting Stage" {
        [A_0] --> [AND || OR ? Invert]
        [B_0] --> [AND || OR || SUB || SLT ? Invert]
        [SUB || SLT]
}

package "Combining Stage" {
        [AND || OR ? Invert] --> [ADD]
        [AND || OR || SUB || SLT ? Invert] --> [ADD]
        [SUB || SLT] --> [ADD]

        [AND || OR ? Invert] --> [NOR]
        [AND || OR || SUB || SLT ? Invert] --> [NOR]

        [AND || OR ? Invert] --> [NAND]
        [AND || OR || SUB || SLT ? Invert] --> [NAND]

        [AND || OR ? Invert] --> [XOR]
        [AND || OR || SUB || SLT ? Invert] --> [XOR]
}

package "Selection Stage" {
        [ADD] --> [Out_0]
        [ADD] --> [Carry_0]
        [NOR] --> [Out_0]
        [NOR] --> [Carry_0]
        [NAND] --> [Out_0]
        [NAND] --> [Carry_0]
        [XOR] --> [Out_0]
        [XOR] --> [Carry_0]
}

@enduml
